const { Configuration, OpenAIApi } = require("openai");
const fetch = require('node-fetch');
const fs = require('fs');
const { promisify } = require('util');
const writeFile = promisify(fs.writeFile);
const path = require('path');

const configuration = new Configuration({
  apiKey: process.env.API_KEY_VALUE,
});

const openai = new OpenAIApi(configuration);

const names = [
	"Albert Einstein",
	"William Shakespeare",
	"Leonardo da Vinci",
	"Abraham Lincoln",
	"Mahatma Gandhi",
	"Isaac Newton",
	"George Washington",
	"Nelson Mandela",
	"Thomas Edison",
	"Sigmund Freud",
	"Winston Churchill",
	"Charles Darwin",
	"Martin Luther King Jr.",
	"Cleopatra",
	"Julius Caesar",
	"Christopher Columbus",
	"Alexander the Great",
	"Queen Elizabeth I",
	"Napoleon Bonaparte",
	"Vincent van Gogh",
	"Jane Austen",
	"Mother Teresa",
	"Stephen Hawking",
	"Mark Twain",
	"Frida Kahlo",
	"Elon Musk",
	"Oprah Winfrey",
	"Barack Obama",
	"Bill Gates",
	"J.K. Rowling",
	"David Bowie",
	"Angelina Jolie",
	"Lady Gaga",
	"Tom Hanks",
	"Taylor Swift",
	"Steve Jobs",
	"Ellen DeGeneres",
	"Michael Jordan",
	"Serena Williams",
	"Muhammad Ali",
	"Michael Jackson",
	"Madonna",
	"Leonardo DiCaprio",
	"Johnny Depp",
	"Beyoncé",
	"Kim Kardashian",
	"Brad Pitt",
	"Cristiano Ronaldo",
	"Lionel Messi",
	"Dwayne \"The Rock\" Johnson",
	"Miley Cyrus",
	"Rihanna",
	"Jennifer Lawrence",
	"Will Smith",
	"Justin Bieber",
	"Robert Downey Jr.",
	"Katy Perry",
	"Selena Gomez",
	"Ariana Grande",
	"Jennifer Aniston",
	"Dalai Lama",
	"Malala Yousafzai",
	"Aung San Suu Kyi",
	"Greta Thunberg",
	"Richard Branson",
	"George R.R. Martin",
	"Quentin Tarantino",
	"J.R.R. Tolkien",
	"Stan Lee",
	"Maya Angelou",
	"Marie Curie",
	"Amelia Earhart",
	"Ada Lovelace",
	"Rosalind Franklin",
	"Coco Chanel",
	"Ruth Bader Ginsburg",
	"Anne Frank",
	"Emily Dickinson",
	"Rosa Parks",
	"Harriet Tubman",
	"Joan of Arc",
	"Virginia Woolf",
	"Helen Keller",
	"Susan B. Anthony",
	"Audrey Hepburn",
	"Pablo Picasso",
	"Walt Disney",
	"Galileo Galilei",
	"Wolfgang Amadeus Mozart",
	"Plato",
	"Karl Marx",
	"Confucius",
	"Aristotle",
	"Socrates",
	"Friedrich Nietzsche",
	"Genghis Khan",
	"Marco Polo",
	"Florence Nightingale",
	"Sitting Bull",
	"Maharishi Mahesh Yogi",
	"Jim Henson",
	"Fred Rogers",
	"Mister Spock",
	"Hannibal Lecter",
	"Darth Vader",
	"Yoda",
	"Captain America",
	"Superman",
	"Thor",
	"Loki",
	"Gandalf",
	"Aragorn",
	"Samwise Gamgee",
	"Gollum",
	"Jon Snow",
	"Daenerys Targaryen",
	"Walter White",
	"Tony Soprano",
	"Don Draper",
	"Meredith Grey",
	"Chandler Bing",
	"Rachel Green",
	"Ross Geller",
	"Monica Geller",
	"Phoebe Buffay",
	"Joey Tribbiani",
	"Carrie Bradshaw",
	"Charlotte York",
	"Miranda Hobbes",
	"Samantha Jones",
	"John Lennon",
	"Paul McCartney",
	"George Harrison",
	"Ringo Starr",
	"Freddie Mercury",
	"Kurt Cobain",
	"Elvis Presley",
	"Bob Marley",
	"John F. Kennedy",
	"Marilyn Monroe",
	"Marlon Brando",
	"Grace Kelly",
	"Charlie Chaplin",
	"Cary Grant",
	"Judy Garland",
	"Lucille Ball",
	"Neil Armstrong",
	"Buzz Aldrin",
	"Jackie Robinson",
	"Babe Ruth",
	"Michael Phelps",
	"Usain Bolt",
	"Simone Biles",
	"Mia Hamm",
	"Pele",
	"Shaquille O'Neal",
	"Bart Simpson",
	"Homer Simpson",
	"Marge Simpson",
	"Lisa Simpson",
	"Naruto Uzumaki",
	"Goku",
	"Luffy",
	"Ichigo Kurosaki",
	"Pikachu",
	"Ash Ketchum",
	"Optimus Prime",
	"Megatron",
	"The Terminator",
	"RoboCop",
	"Nelson Rockefeller",
	"Elizabeth Barrett Browning",
	"Chuck Yeager",
	"Gloria Steinem",
	"Alexander Hamilton",
	"John Locke",
	"Diego Maradona",
	"Mikhail Gorbachev",
	"Luciano Pavarotti",
	"Henry Ford",
	"John F. Kennedy Jr.",
	"Marilyn Monroe",
	"Agatha Christie",
	"Johann Sebastian Bach",
	"Sergei Rachmaninoff",
	"Benjamin Franklin",
	"Ludwig van Beethoven",
	"Pablo Picasso",
	"Claude Monet",
	"Vincente Minnelli",
	"Jackie Kennedy Onassis",
	"Audrey Hepburn",
	"Richard Nixon",
	"Eleanor Roosevelt",
	"Margaret Thatcher",
	"Winston Churchill",
	"Salvador Dali",
	"Alfred Hitchcock",
	"Neil Armstrong",
	"Isaac Asimov",
	"Norman Rockwell",
	"Jimi Hendrix",
	"Jacqueline du Pré",
	"Kurt Cobain",
	"Dalai Lama XIV",
	"Harriet Beecher Stowe",
	"Oscar Wilde",
	"George Orwell",
	"Friedrich Nietzsche",
	"Henry David Thoreau",
	"Walt Disney",
	"Carl Sagan",
	"Enrico Fermi",
	"Stephen King",
	"Robert Frost",
	"E.E. Cummings",
	"Samuel Beckett",
	"Bob Dylan",
	"William Faulkner",
	"Ernest Hemingway",
	"Patti Smith",
	"Susan Sontag",
	"Shirley Chisholm",
	"Jackie Robinson",
	"Tyra Banks",
	"Simone Biles",
	"Angela Merkel",
	"Aung San Suu Kyi",
	"Emmeline Pankhurst",
	"Grace Kelly",
	"Bette Davis",
	"Marlene Dietrich",
	"Joan Crawford",
	"Greta Garbo",
	"Robert De Niro",
	"Clint Eastwood",
	"Sidney Poitier",
	"Gene Kelly",
	"Charlie Chaplin",
	"Federico Fellini",
	"Martin Scorsese",
	"Stanley Kubrick",
	"Ridley Scott",
	"Pedro Almodóvar",
	"Quentin Tarantino",
	"Clint Barton",
	"Natasha Romanoff",
	"T'Challa",
	"Tony Stark",
	"Captain America",
	"Bruce Wayne",
	"Clark Kent",
	"Diana Prince",
	"Peter Parker",
	"Wolverine",
	"John McClane",
	"Indiana Jones",
	"Rocky Balboa",
	"Frankenstein's Monster",
	"Dracula",
	"Sherlock Holmes",
	"Robin Hood",
	"King Arthur",
	"Captain Ahab",
	"The Mad Hatter",
	"Elizabeth Bennet",
	"Jane Eyre",
	"The Count of Monte Cristo",
	"Charles Babbage",
	"Ada Lovelace",
	"Marie Curie",
	"Albert Schweitzer",
	"Rachel Carson",
	"Martin Luther",
	"Galileo Galilei",
	"Johannes Kepler",
	"Florence Nightingale",
	"Susan B. Anthony",
	"Jane Addams",
	"Emma Goldman",
	"Albert Camus",
	"Queen Victoria",
	"Otto von Bismarck",
	"Winston Churchill",
	"Mao Zedong",
	"Benito Mussolini",
	"Mikhail Gorbachev",
	"Margaret Thatcher",
	"Nelson Mandela",
	"George Washington",
	"Peter the Great",
	"Catherine the Great",
	"Vladimir Lenin",
	"Joseph Stalin",
	"Franklin D. Roosevelt",
	"John F. Kennedy",
	"Dwight D. Eisenhower",
	"Ronald Reagan",
	"Abraham Lincoln",
	"Thomas Jefferson",
	"George W. Bush",
	"Barack Obama",
	"Donald Trump",
	"Bill Clinton",
	"Angela Merkel",
	"Emperor Meiji",
	"Mehmed II",
	"Suleiman the Magnificent",
	"Napoleon Bonaparte",
	"Charles de Gaulle",
	"François Mitterrand",
	"Emmanuel Macron",
	"Viktor Orban",
	"Vladimir Putin",
	"Alexander Lukashenko",
	"Kim Jong-un",
	"Mahatma Gandhi",
	"Jawaharlal Nehru",
	"Indira Gandhi",
	"Manmohan Singh",
	"Narendra Modi",
	"Atal Bihari Vajpayee",
	"Imran Khan",
	"Pervez Musharraf",
	"Benazir Bhutto",
	"Abdel Fattah el-Sisi",
	"Gamal Abdel Nasser",
	"Hosni Mubarak",
	"Anwar Sadat",
	"Mohammed Morsi",
	"Yasser Arafat",
	"Golda Meir",
	"David Ben-Gurion",
	"Menachem Begin",
	"Yitzhak Rabin",
	"Shimon Peres",
	"Benjamin Netanyahu",
	"Recep Tayyip Erdogan",
	"Mustafa Kemal Ataturk",
	"Ismet Inonu",
	"Turgut Ozal",
	"Jacques Chirac",
	"Francois Hollande",
	"Charles Michel",
	"Alexander II",
	"Peter Stuyvesant",
	"Juan Carlos I",
	"Fidel Castro",
	"Raúl Castro",
	"Che Guevara",
	"Hugo Chávez",
	"Nicolás Maduro",
	"Augusto Pinochet",
	"Salvador Allende",
	"Rafael Trujillo",
	"Haitian Revolution Leaders",
	"François Duvalier",
	"Jean-Claude Duvalier",
	"Laurent-Désiré Kabila",
	"Mobutu Sese Seko",
	"Joseph Kabila",
	"Patrice Lumumba",
	"Jonas Savimbi",
	"Jomo Kenyatta",
	"Daniel arap Moi",
	"Mwai Kibaki",
	"Uhuru Kenyatta",
	"Julius Nyerere",
	"Idi Amin",
	"Yoweri Museveni",
	"Kwame Nkrumah",
	"Jerry Rawlings",
	"Robert Mugabe",
	"Ian Smith",
	"Nelson Chamisa",
	"Seretse Khama",
	"Samora Machel",
	"Robert Sobukwe",
	"Winnie Madikizela-Mandela",
	"Albert Luthuli",
	"Steve Biko"
];

const generateAvatar = async (name) => {
  const prompt = `Create a photo-realistic portrait of ${name}`;

  const response = await openai.createImage({
    prompt: prompt,
    n: 1,
    size: "256x256",
  });

  const imageUrl = response.data.data[0].url
  console.log(imageUrl);
  const imageResponse = await fetch(imageUrl);

  return await imageResponse.buffer();
};

const saveAvatar = async (name, buffer) => {
  const fileName = `avatars/${name.replace(/[^a-zA-Z0-9]/g, '_')}.png`;
  const result = await writeFile(fileName, buffer);
  console.log(result);
  console.log(`Saved ${fileName}`);
};

const createAvatarsFolder = () => {
  if (!fs.existsSync('avatars')) {
    fs.mkdirSync('avatars');
  }
};

const avatarExists = (name) => {
    const fileName = `avatars/${name.replace(/[^a-zA-Z0-9]/g, '_')}.png`;
    return fs.existsSync(path.resolve(fileName));
  };
  
  const main = async () => {
    createAvatarsFolder();
  
    for (const name of names) {
      try {
        if (avatarExists(name)) {
          console.log(`Avatar for ${name} already exists, skipping...`);
          continue;
        }
  
        const imageBuffer = await generateAvatar(name);
        await saveAvatar(name, imageBuffer);
      } catch (err) {
        console.error(`Failed to generate avatar for ${name}: ${err.message}`);
      }
    }
  };
  
  main();